### Numpy Learning


In [2]:
import numpy as np

In [3]:
myarr = np.array([1,23,33,45])

In [4]:
myarr

array([ 1, 23, 33, 45])

In [5]:
myarr = np.array([[1,23,33,45,90]])

In [6]:
myarr

array([[ 1, 23, 33, 45, 90]])

In [7]:
myarr[0,1]

np.int64(23)

In [8]:
myarr.shape

(1, 5)

In [9]:
myarr.dtype

dtype('int64')

In [10]:
myarr

array([[ 1, 23, 33, 45, 90]])

In [11]:
myarr[0,2]

np.int64(33)

In [12]:
myarr[0,2] = 40

In [13]:
myarr

array([[ 1, 23, 40, 45, 90]])

### Array Creation : Conversion from other python structure 

In [14]:
listarray = np.array([[1,2,3], [4,6,8]])

In [15]:
listarray

array([[1, 2, 3],
       [4, 6, 8]])

In [16]:
listarray.shape

(2, 3)

In [17]:
listarray.size

6

In [18]:
listarray[0,1] = 20

In [19]:
listarray

array([[ 1, 20,  3],
       [ 4,  6,  8]])

### Intrinsic Numpy Array Creation 

In [23]:
zero = np.zeros((2,4))

In [24]:
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
rng = np.arange(10)

In [26]:
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
lspace = np.linspace(1,40,10)

In [35]:
lspace

array([ 1.        ,  5.33333333,  9.66666667, 14.        , 18.33333333,
       22.66666667, 27.        , 31.33333333, 35.66666667, 40.        ])

In [39]:
emp = np.empty((3,4))

In [40]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        6.23047842e-307],
       [8.45593934e-307, 7.56593017e-307, 1.11258854e-306,
        1.33512376e-306],
       [9.34609790e-307, 8.45590539e-307, 8.34445562e-308,
        3.08148792e-033]])

In [54]:
rng1 = np.arange(99)

In [55]:
rng1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [56]:
rng1.reshape(3, 33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [57]:
rng1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])