### Numpy Learning


In [3]:
import numpy as np

In [4]:
myarr = np.array([1,23,33,45])

In [5]:
myarr

array([ 1, 23, 33, 45])

In [6]:
myarr = np.array([[1,23,33,45,90]])

In [7]:
myarr

array([[ 1, 23, 33, 45, 90]])

In [8]:
myarr[0,1]

np.int64(23)

In [9]:
myarr.shape

(1, 5)

In [10]:
myarr.dtype

dtype('int64')

In [11]:
myarr

array([[ 1, 23, 33, 45, 90]])

In [15]:
myarr[0,2]

np.int64(33)

In [16]:
myarr[0,2] = 40

In [17]:
myarr

array([[ 1, 23, 40, 45, 90]])

### Array Creation : Conversion from other python structure 

In [18]:
listarray = np.array([[1,2,3], [4,6,8]])

In [19]:
listarray

array([[1, 2, 3],
       [4, 6, 8]])

In [20]:
listarray.shape

(2, 3)

In [21]:
listarray.size

6

In [23]:
listarray[0,1] = 20

In [24]:
listarray

array([[ 1, 20,  3],
       [ 4,  6,  8]])